Hierarchies with multiple parents or non-standard root definition
oasis-tcs/odata-specs pull request #1
Opened 2023-06-01 05:42 UTC by HeikoTheissen

2023-06-07 07:15 UTC, ralfhandl commented on odata-data-aggregation-ext/7 Examples.md
> +PATCH /service/SalesOrganizations('Mars')/Relations
```suggestion
POST /service/SalesOrganizations('Mars')/Relations
```

2023-06-07 07:28 UTC, HeikoTheissen commented on odata-data-aggregation-ext/7 Examples.md
> +                     PropertyPath="Relations/Superordinate" />
This navigation property path consists of a collection-valued navigation property followed by a single-valued one.

2023-06-12 06:37 UTC, HeikoTheissen commented on odata-data-aggregation-ext/5 Vocabulary for Data Aggregation.md
> +- `isroot` tests if the given entity is a root node of the hierarchy.
Do we want to test for root nodes or for start nodes?

2023-06-14 16:01 UTC, HeikoTheissen commented on odata-data-aggregation-ext/6 Hierarchical Transformations.md
> +If the `Aggregation.UpPath` annotation of $y$ contains the node identifier of $y$, a cycle has been detected and $ρ(y,x)$ is additionally annotated with term `Aggregation.Cycle`, qualifier $Q$ and va
Assume A > B > C > D and D > C where ">" means "parent of". Then the entry
```json
{"NodeID": "C", "@Aggregation.Cycle": true, "@Aggregation.UpPath": ["D", "C", "B", "A"]}
```
makes clear there is a cycle C-D-C. Without that entry, the cycle would be unclear.

2023-06-19 11:26 UTC, ralfhandl approved these changes

2023-06-19 13:10 UTC, HeikoTheissen commented on odata-data-aggregation-ext/7 Examples.md
> +{ "Superordinate@bind": "SalesOrganizations('Sales')" }
Is it possible to achieve the same effect with a request where both segments appear together?

2023-06-21 12:55 UTC, HeikoTheissen commented on odata-data-aggregation-ext/5 Vocabulary for Data Aggregation.md
> +- The `ParentNavigationProperty` allows navigation to the instance or instances representing the parent nodes. It MUST be a collection-valued or nullable single-valued navigation property path that a
Give an example for cycles without temporality.

2023-06-26 14:22 UTC, GeraldKrause requested changes

2023-06-26 14:52 UTC, HeikoTheissen commented on odata-data-aggregation-ext/6 Hierarchical Transformations.md
> +⚠ Example ##ex: If the child of Atlantis is also its parent:
What's wrong with the example?

2023-06-26 14:56 UTC, HeikoTheissen commented on odata-data-aggregation-ext/5 Vocabulary for Data Aggregation.md
> +- identifying entities that are part of the recursive hierarchy through a single primitive property called the _node identifier_. The entities in the hierarchy are called _nodes_.
Check again after my latest commit.

2023-06-26 16:29 UTC, GeraldKrause commented on odata-data-aggregation-ext/6 Hierarchical Transformations.md
> +⚠ Example ##ex: If the child of Atlantis is also its parent:
I got confused and thought "its" relates to the "child of Atlantis". 
```suggestion
⚠ Example ##ex: If the child of Atlantis is also the parent of Atlantis:
```

2023-06-30 09:04 UTC, GeraldKrause approved these changes
Approved with the changes discussed in TC call 2023-06-28

2023-06-30 09:04 UTC, merged