ODATA-1564
oasis-tcs/odata-specs pull request #107
Opened 2023-08-16 17:14 UTC by ralfhandl

2023-08-17 06:16 UTC, HeikoTheissen submitted a review, later dismissed

2023-08-17 12:38 UTC, HeikoTheissen submitted a review, later dismissed

2023-11-15 17:29 UTC, HeikoTheissen requested changes

2023-11-15 17:29 UTC, HeikoTheissen commented on odata-protocol/11.7 Batch Requests.md
>  Host: myserver.mydomain.org:1234
Add a request body.

2023-11-16 09:09 UTC, HeikoTheissen approved these changes

2023-11-16 09:21 UTC, ralfhandl commented
@HeikoTheissen Thanks!

2023-11-22 16:12 UTC, merged