ODATA-1525
oasis-tcs/odata-specs pull request #151
Opened 2023-08-18 12:46 UTC by ralfhandl

2023-08-18 12:59 UTC, HeikoTheissen requested changes

2023-08-18 12:59 UTC, HeikoTheissen commented on odata-protocol/10 Context URL.md
> +`$expand=*` is treated as if the corresponding navigation properties were explicitly expanded.
```suggestion
The context URL has no shortcut for representing the list of all navigation properties;
`$expand=*` is treated as if all navigation properties were explicitly expanded.
```
Is that what you mean?

2023-08-18 13:03 UTC, ralfhandl commented on odata-protocol/10 Context URL.md
> +`$expand=*` is treated as if the corresponding navigation properties were explicitly expanded.
Thanks, that is much clearer

2023-08-18 13:08 UTC, HeikoTheissen submitted a review, later dismissed

2023-11-15 16:58 UTC, HeikoTheissen approved these changes

2023-11-15 16:58 UTC, merged