Deprecate SRID value `variable`
oasis-tcs/odata-specs pull request #1937
Opened 2024-05-17 12:52 UTC by ralfhandl

Fixes #1935

2024-05-17 15:27 UTC, sthagen approved these changes
LGTM, thanks a lot. Much appreciated.

2024-05-21 11:03 UTC, HeikoTheissen requested changes

2024-05-21 12:14 UTC, ralfhandl commented on odata-json-format/1 Introduction.md
> +[Section ##StructuralProperty], [Section ##InformativeReferences]|
4.01 referenced GeoJSON-2008, which we removed: https://docs.oasis-open.org/odata/odata-json-format/v4.01/odata-json-format-v4.01.html#sec_NonNormativeReferences

2024-05-21 13:47 UTC, HeikoTheissen commented on odata-csdl/1 Introduction.md
> +[ 1935](https://github.com/oasis-tcs/odata-specs/issues/1935)
This is not resolved.

2024-05-21 14:34 UTC, HeikoTheissen approved these changes

2024-06-13 12:15 UTC, ralfhandl commented
Rebuilt after merging `main`

2024-06-13 18:10 UTC, sthagen approved these changes
Ship it!

2024-06-20 17:27 UTC, sthagen approved these changes
Getting better all the time. Thanks.

2024-06-26 15:31 UTC, ralfhandl commented on odata-csdl/1 Introduction.md
> +response bodies.
```suggestion
Representation of primitive type values within a URL is defined by the rule `primitiveLiteral` in [OData-ABNF](#ODataABNF).
Representation within request and response bodies is format specific.
```

2024-06-26 15:38 UTC, ralfhandl commented on odata-csdl/1 Introduction.md
> +format does not define a representation for instance-specific spatial reference systems.
```suggestion
Services SHOULD NOT use the special value `variable` as some formats, for example [OData-JSON](#ODataJSON), do not define a representation for instance-specific spatial reference systems.
```

2024-06-26 15:42 UTC, HeikoTheissen approved these changes

2024-06-26 15:42 UTC, merged

2024-06-26 15:42 UTC, mikepizzo reviewed
I don't know that the reference to ODATA-JSON is required, but okay if others feel strongly.