Transient entities in JSON
oasis-tcs/odata-specs pull request #1942
Opened 2024-05-29 08:46 UTC by ralfhandl

Fixes #1928.

2024-05-29 08:51 UTC, ralfhandl commented on odata-json-format/4 Common Characteristics.md
>  the canonical URL MUST be used as the entity-id.
This seems to contradict the preceding statement that 

> clients MUST treat entities with neither `id` control
> information nor a full set of key properties as transient entities.

Also it is not clear to me who must do this: the client or the service?

2024-05-29 08:54 UTC, ralfhandl commented on odata-json-format/4 Common Characteristics.md
>  the canonical URL MUST be used as the entity-id.
This seems to contradict the preceding statement that 

> clients MUST treat entities with neither `id` control
> information nor a full set of key properties as transient entities.

Also it is not clear to me who must do this: the client or the service?

2024-06-03 16:07 UTC, falbert-ptc approved these changes

2024-06-12 15:22 UTC, ralfhandl commented on odata-json-format/4 Common Characteristics.md
>  Entities with `id` equal to `null` cannot be
```suggestion
Transient entities cannot be
```

2024-06-12 15:27 UTC, ralfhandl commented on odata-json-format/4 Common Characteristics.md
> +between transient entities by injecting an entity reference.
Integrate into previous sentence, make version dependency explicit.

2024-06-13 14:08 UTC, HeikoTheissen requested changes

2024-06-13 14:08 UTC, HeikoTheissen commented on odata-json-format/4 Common Characteristics.md
>  entities need not have the `id` control information, and 4.01
```suggestion
and have the `null` value. In 4.01 or higher payloads transient
entities need not have the `id` control information, and 4.01 or higher
```

2024-06-13 14:38 UTC, HeikoTheissen commented on odata-json-format/4 Common Characteristics.md
>  clients MUST treat entities with neither `id` control
```suggestion
clients receiving such payloads MUST treat entities with neither `id` control
```
If a 4.0 client receives `"@id": null` and a partial key only, is it bound by this statement?

2024-06-13 14:56 UTC, HeikoTheissen approved these changes

2024-07-11 09:45 UTC, HeikoTheissen submitted a review, later dismissed

2024-07-16 15:12 UTC, HeikoTheissen requested changes

2024-07-16 15:12 UTC, HeikoTheissen commented on odata-json-format/1 Introduction.md
> +`Core.ContentId` in transient entities|
```suggestion
`Core.ContentID` in transient entities| 
```

2024-07-16 15:12 UTC, HeikoTheissen commented on odata-json-format/1 Introduction.md
> +Reference transient entities via `Core.ContentId`|
```suggestion
Reference transient entities via `Core.ContentID`| 
```

2024-07-18 09:00 UTC, HeikoTheissen reviewed
Wordsmithing

2024-07-18 09:00 UTC, HeikoTheissen commented on odata-json-format/1 Introduction.md
> +Transient entities can be identifiable|
```suggestion
Allow `@id` for self-referencing transient entities| 
```

2024-07-18 09:08 UTC, ralfhandl commented on odata-json-format/4 Common Characteristics.md
> +[entity reference](#EntityReference) instead of repeating the transient entity.
We haven't defined or used "self-reference" anywhere.

The current clumsier text uses existing wording from Protocol.

2024-07-18 09:09 UTC, ralfhandl commented on odata-protocol/1 Introduction.md
> +and they may have an entity id if a repeated occurrence in a response needs to be replaced with an entity reference.
Intentionally used existing (and somewhat clumsier) wording.

2024-07-18 20:05 UTC, falbert-ptc approved these changes

2024-07-24 15:15 UTC, merged