Style improvements
oasis-tcs/odata-specs pull request #1979
Opened 2024-08-27 16:11 UTC by HeikoTheissen

* Replace the right single quote with a straight single quote in monospaced text and math formulas
* Split `\matrix` formulas across several lines of Markdown (easier to read in the authoritative document)
* Allow switching the HTML documents between light and dark mode

2024-08-27 16:13 UTC, HeikoTheissen commented on styles/odata.css
> +  }
The hardest part is still missing: What is a suitable style for dark mode? Should we ask the OASIS colleagues who provided us with the initial Markdown template?

2024-08-28 08:12 UTC, ralfhandl requested changes
Please revert the changes to single-quotes

2024-08-28 08:39 UTC, ralfhandl submitted a review, later dismissed

2024-08-28 10:16 UTC, ralfhandl approved these changes

2024-08-28 11:10 UTC, ralfhandl submitted a review, later dismissed

2024-08-28 14:13 UTC, ralfhandl approved these changes

2024-08-28 15:15 UTC, mikepizzo approved these changes

2024-08-28 15:18 UTC, merged