Context fragment of contained single entity
oasis-tcs/odata-specs pull request #2009
Opened 2024-10-03 07:29 UTC by HeikoTheissen

Fixes #2000

2024-10-03 12:31 UTC, ralfhandl reviewed
+1, only one comment

2024-10-03 12:31 UTC, ralfhandl commented on odata-protocol/10 Context URL.md
> +    {context-url}#{single-navprop}
In line 25 above we define

> - `{entity-set}` is the name of an entity set or path to a containment navigation property

Please add a definition for `{single-navprop}` and reduce the definition of `{entity-set}` to collection-valued nav props.

2024-10-10 11:30 UTC, ralfhandl requested changes
I really think that the text will be easier if we define
* `{entity-set}` is the name of an entity set or path to a collection-valued containment navigation property
* `{single-entity}` is the name of a singleton or path to a single-valued containment navigation property

and then use these definitions in the text below

2024-10-10 13:46 UTC, ralfhandl requested changes
Good so far. Only nit is that `{singleton}` also appears in 
* section 10.8 Projected Entity
* section 10.10 Expanded Entity

and should be replaced with `{single-entity}`

2024-10-10 14:08 UTC, ralfhandl approved these changes

2024-10-17 06:58 UTC, HeikoTheissen commented on odata-protocol/10 Context URL.md
>  `{type-name}` of the returned entity.
This cannot cannot occur, because the response in this section is always _one_ entity, not a (sub)set.

2024-10-23 15:50 UTC, HeikoTheissen commented on odata-protocol/10 Context URL.md
>  single entity set, the `{select-list}` is instead appended to the
```suggestion
If the entity is not bound to an entity set, the `{select-list}` is instead appended to the
```

2024-10-23 15:55 UTC, ralfhandl commented on odata-protocol/10 Context URL.md
>  If the entity is not bound to an entity set, such as an entity
```suggestion
If the entity is not contained in an entity set, such as an entity
```

2024-10-23 16:04 UTC, ralfhandl commented on odata-protocol/10 Context URL.md
>  entity,
```suggestion
- `{entity}` is the canonical URL for an
entity within a collection,
```

2024-10-23 16:06 UTC, ralfhandl commented on odata-protocol/10 Context URL.md
> +- `{entity-set}` is the name of an entity set [#OData-CSDL#EntitySet]
```suggestion
- `{entity-collection}` is the name of an entity set [#OData-CSDL#EntitySet]
```

2024-10-23 16:12 UTC, ralfhandl commented on odata-protocol/10 Context URL.md
> +- `{single-entity}` is the name of a singleton or the canonical path to a single-valued containment navigation property,
```suggestion
- `{entity-singleton}` is the name of a singleton or the canonical path to a single-valued containment navigation property,
```

2024-10-23 16:29 UTC, ralfhandl commented on odata-protocol/10 Context URL.md
> +    {context-url}#{single-entity}
```suggestion
```

Cover "contained/implicit singletons" in section Singleton

2024-10-23 16:37 UTC, ralfhandl commented on odata-protocol/10 Context URL.md
>      {context-url}#{entity-set}{/type-name}/$entity
This section and the preceding one only applies if the request has a type-cast segment

2024-10-24 08:08 UTC, HeikoTheissen commented
Sections 10.2, 10.3 and 10.4. form a triplet for the cases
- collection of entities
- one entity from a collection
- a singleton (entity) that is not contained in a collection (in this case, the `{type-name}` variant never occurs).

But in later sections, this triplet pattern is violated. There are no sections for "Derived Singleton", "Projected Singleton" or "Expanded Singleton". And "Operations Results" and "Delta Payload" lump all three cases together.

Consider describing the triplet as orthogonal to the other ingredients (derivation, projection, expansion, operation, delta).

2024-11-06 16:47 UTC, ralfhandl commented
We decided to merge sections 10.13 to 10.15 and get rid of 10.16

2024-11-07 07:42 UTC, HeikoTheissen commented
https://github.com/oasis-tcs/odata-specs/blob/e28bd9684300257fb2829a57dba5c54e886ac969/odata-protocol/10%20Context%20URL.md?plain=1#L473-L477

If there is a special context URL format for a property of a specific entity, why not also for a specific entity in its entirety?

```
http://host/service/Customers(1)
http://host/service/$metadata#Customers/$entity  /* context URL as specified */
http://host/service/$metadata#Customers(1) /* why not this? */
```

2024-11-07 13:53 UTC, ralfhandl commented
> If there is a special context URL format for a property of a specific entity, why not also for a specific entity in its entirety?

[10 Context URL](https://docs.oasis-open.org/odata/odata/v4.02/csd01/part1-protocol/odata-v4.02-csd01-part1-protocol.html#ContextURL) claims that

> The context URL makes response payloads “self-contained”, allowing a recipient to retrieve metadata, resolve references, and **construct canonical links omitted from response payloads in certain optimized formats.**

[4.5.8 Control Information: id (odata.id)](https://docs.oasis-open.org/odata/odata-json-format/v4.02/csd01/odata-json-format-v4.02-csd01.html#ControlInformationidodataid) requires that

> The `id` control information MUST appear in responses if [...] any of a non-transient entity’s key fields are omitted from the response [...]

This means that a (JSON) representation of a full or projected entity has enough information to construct the canonical URL from the entity set name alone included in the context URL, whereas for properties of an entity the context URL in addition needs to include the key values. Same for "implicit contained entity sets" which also include the key values of the container(s).

2024-11-20 16:25 UTC, mikepizzo commented on odata-protocol/10 Context URL.md
> +If the entities are not members of one
```suggestion
If the entities are not members of a single
```

2024-11-20 16:28 UTC, ralfhandl commented on odata-protocol/10 Context URL.md
> +or an entity addressed by a single-valued collection-valued containment
```suggestion
or an entity addressed by a single-valued containment
```

2024-11-20 16:35 UTC, ralfhandl approved these changes

2024-11-20 16:36 UTC, ralfhandl commented on odata-protocol/10 Context URL.md
> +or a collection addressed by a collection-valued containment navigation property
```suggestion
or a collection addressed by a containment navigation property
```

2024-11-20 16:38 UTC, ralfhandl approved these changes

2024-11-20 16:39 UTC, ralfhandl commented on odata-protocol/10 Context URL.md
> +the type `{type-name}` of the returned entity.
```suggestion
the `{type-name}` of the returned entity.
```

2024-11-20 16:42 UTC, mikepizzo approved these changes

2024-11-20 16:42 UTC, ralfhandl approved these changes

2024-11-20 16:43 UTC, merged