`@etag: ""`
oasis-tcs/odata-specs pull request #2035
Opened 2024-11-28 08:44 UTC by HeikoTheissen

Fixes #2021

2024-11-28 13:14 UTC, ralfhandl requested changes

2024-11-28 13:14 UTC, ralfhandl commented on odata-protocol/11.4 Data Modification.md
> +is specified with an empty string as value.
Better add this after https://github.com/oasis-tcs/odata-specs/blob/ff14732045e46423b0752921e720d46b13827c5c/odata-protocol/11.4%20Data%20Modification.md?plain=1#L1168

and use the same format-agnostic formulation.

So far we do not mention `@etag` in Protocol.

2024-11-28 15:44 UTC, ralfhandl commented on odata-json-format/4 Common Characteristics.md
> +see [#OData-Protocol#UpdateaCollectionofEntities].
```suggestion

The special value `"@etag": "*"` is equivalent to the header `If-Match: *`, and the special value `"@etag": ""` is equivalent to the header `If-None-Match: *`,
see [#OData-Protocol#UpdateaCollectionofEntities].
```

2024-11-28 15:45 UTC, ralfhandl commented on odata-json-format/4 Common Characteristics.md
Also mention this in the "Changes" section, similar to Protocol.

2024-11-29 08:46 UTC, ralfhandl commented on odata-json-format/1 Introduction.md
>  [Section ##DeletedEntity] |
Do you want to remove the space before the `|` here, too?

2024-11-29 08:49 UTC, ralfhandl approved these changes

2024-11-29 09:46 UTC, ralfhandl approved these changes

2025-02-12 16:12 UTC, mikepizzo approved these changes

2025-02-12 16:13 UTC, merged