ODATA-1609
oasis-tcs/odata-specs pull request #212
Opened 2023-11-09 07:02 UTC by HeikoTheissen

https://issues.oasis-open.org/browse/ODATA-1609

2023-11-09 07:41 UTC, HeikoTheissen commented
Does this change merit mention in section 1.1?

2023-11-09 07:47 UTC, ralfhandl reviewed
Minor nits, see proposals

2023-11-09 07:47 UTC, ralfhandl commented on odata-protocol/11.4 Data Modification.md
> +even if the requested content could not be returned.
```suggestion
independent of whether the requested content could be returned.
```

2023-11-09 07:47 UTC, ralfhandl commented on odata-protocol/11.4 Data Modification.md
> +request included a [Prefer header](#Preferencereturnrepresentationandreturnminimal)
```suggestion
request included a [`Prefer` header](#Preferencereturnrepresentationandreturnminimal)
```

2023-11-09 07:47 UTC, ralfhandl commented on odata-protocol/11.4 Data Modification.md
> +can determine the created entity with a [query collection](#QueryingCollections).
```suggestion
can determine the created entity with a [collection query](#QueryingCollections).
```

2023-11-09 07:50 UTC, ralfhandl commented
> Does this change deserve mention in section 1.1?

I'd prefer it to be mentioned as we modified/relativized a MUST requirement.

2023-11-09 08:49 UTC, ralfhandl reviewed
Sorry, more nits

2023-11-09 08:49 UTC, ralfhandl commented on odata-protocol/1 Introduction.md
> +Response code 2xx after successful data modification if requested response could not be constructed|
```suggestion
Response code `204 No Content` after successful data modification if requested response could not be constructed| 
```

2023-11-09 08:49 UTC, ralfhandl commented on odata-protocol/11.4 Data Modification.md
> +the [`Prefer: return` header](#Preferencereturnrepresentationandreturnminimal).
```suggestion
the [`return`](#Preferencereturnrepresentationandreturnminimal) preference.
```
Align with most common reference format

2023-11-09 08:49 UTC, ralfhandl commented on odata-protocol/11.4 Data Modification.md
> +request included a [`Prefer` header](#Preferencereturnrepresentationandreturnminimal)
```suggestion
request included a [`Prefer`](#Preferencereturnrepresentationandreturnminimal) header
```

2023-11-09 09:10 UTC, ralfhandl approved these changes

2023-11-09 15:14 UTC, ralfhandl submitted a review, later dismissed

2023-11-10 15:03 UTC, ralfhandl reviewed
Minor nit

2023-11-10 15:04 UTC, HeikoTheissen commented
> Minor nit

Where is the nit?

2023-11-10 15:06 UTC, ralfhandl reviewed
Here

2023-11-10 15:06 UTC, ralfhandl commented on odata-protocol/8 Header Fields.md
> +`204 No Content` MAY include an `ETag` header with a value reflecting
```suggestion
`204 No Content` MAY include an [`ETag`](#HeaderETag) header with a value reflecting
```

2023-11-10 15:07 UTC, ralfhandl commented on odata-protocol/8 Header Fields.md
> +`204 No Content MAY `include an `ETag` header with a value reflecting
```suggestion
`204 No Content MAY `include an [`ETag`](#HeaderETag) header with a value reflecting
```

2023-11-10 15:08 UTC, ralfhandl requested changes

2023-11-10 15:08 UTC, ralfhandl commented on odata-protocol/8 Header Fields.md
> +`204 No Content MAY `include an `ETag` header with a value reflecting
Make `ETag` a link

2023-11-10 15:10 UTC, ralfhandl approved these changes

2023-11-10 15:12 UTC, ralfhandl submitted a review, later dismissed
Thanks!

2023-11-15 16:30 UTC, ralfhandl approved these changes

2023-11-22 16:24 UTC, ralfhandl approved these changes

2023-11-22 16:31 UTC, merged