ODATA-1624
oasis-tcs/odata-specs pull request #225
Opened 2023-12-07 18:33 UTC by ralfhandl

Fixes #391

2023-12-11 09:57 UTC, HeikoTheissen requested changes

2023-12-11 09:57 UTC, HeikoTheissen commented on odata-protocol/12 Conformance.md
Add an introductory sentence that explains the difference between "unsupported" and "unrecognized".

2023-12-11 11:36 UTC, HeikoTheissen submitted a review, later dismissed

2024-01-11 08:26 UTC, HeikoTheissen approved these changes

2024-02-08 15:28 UTC, HeikoTheissen commented on odata-protocol/12 Conformance.md
> +either follow the specification or fail the request
Why "either" here but not below?

2024-02-08 15:37 UTC, ralfhandl commented on odata-protocol/12 Conformance.md
> +either follow the specification or fail the request
Removed "either" in three places

2024-02-08 15:38 UTC, HeikoTheissen submitted a review, later dismissed

2024-02-23 07:19 UTC, HeikoTheissen approved these changes

2024-04-23 13:31 UTC, HeikoTheissen submitted a review, later dismissed

2024-05-08 16:05 UTC, HeikoTheissen approved these changes

2024-05-08 16:06 UTC, merged