ODATA-1601
oasis-tcs/odata-specs pull request #230
Opened 2023-12-18 13:52 UTC by ralfhandl

2023-12-18 15:06 UTC, HeikoTheissen requested changes

2023-12-18 15:06 UTC, HeikoTheissen commented on odata-protocol/11 Data Service Requests.md
> +<tr><td><code>concat</code></td><td><pre><code>concat(City,', ', Country) eq 'Berlin, Germany'</code></pre></td></tr>
```suggestion
<tr><td><code>concat</code></td><td><pre><code>concat(City,', ',Country) eq 'Berlin, Germany'</code></pre></td></tr>
```

2023-12-18 15:06 UTC, HeikoTheissen commented on odata-url-conventions/5 Query Options.md
> +OrderedCollection concat(OrderedCollection,...,OrderedCollection)
```suggestion
Edm.String concat(Edm.String,…,Edm.String)
Collection concat(Collection,…,Collection)
OrderedCollection concat(OrderedCollection,…,OrderedCollection)
```

2023-12-18 15:06 UTC, HeikoTheissen commented on odata-url-conventions/5 Query Options.md
> +value is the combined text of the strings provided.
```suggestion
value is the concatenation of the strings provided.
```

2023-12-18 15:06 UTC, HeikoTheissen commented on odata-url-conventions/5 Query Options.md
> +If all provided collections are ordered, the result is also ordered.
```suggestion
If all provided collections are ordered, the result is the ordered concatenation of the provided collections.
```

2023-12-18 15:25 UTC, HeikoTheissen approved these changes

2024-02-08 14:17 UTC, ralfhandl commented
Declined

2024-02-08 14:17 UTC, closed without merging