V4.02 CSD01 release candidate
oasis-tcs/odata-specs pull request #252
Opened 2024-02-26 17:12 UTC by ralfhandl

2024-02-26 18:50 UTC, GEricson submitted a review, later dismissed

2024-02-27 07:22 UTC, HeikoTheissen approved these changes

2024-02-27 07:29 UTC, HeikoTheissen requested changes
[OData-CSDL, section 1.1](https://github.com/oasis-tcs/odata-specs/blob/bc64c2f30853c9421c5344f2347178970692b959/docs/odata-csdl-json/odata-csdl-json.md#11-changes-from-earlier-versions) should be sorted by sections.

2024-02-27 13:11 UTC, ralfhandl commented on lib/build-pdf.js
> +  if (doc !== "*" && doc !== name) return;
This change means that PDFs are never generated

2024-02-27 13:43 UTC, HeikoTheissen commented
Must we include ABNF or vocabulary files in the ZIP folders?

2024-02-27 13:52 UTC, HeikoTheissen approved these changes

2024-02-27 13:54 UTC, ralfhandl commented
> Must we include ABNF or vocabulary files in the ZIP folders?

If they are listed in "Additional artifacts" on the title page, we have to include them in the ZIP file.

2024-02-27 13:57 UTC, GeraldKrause approved these changes

2024-02-27 14:01 UTC, HeikoTheissen commented
> If they are listed in "Additional artifacts" on the title page, we have to include them in the ZIP file.

They are not, although the text sometimes refers to certain vocabulary terms.

And changes we made to the context URL and to the URL conventions are also reflected in the ABNF. Doesn't that make the ABNF an additional artifact for them?

2024-02-27 14:06 UTC, ralfhandl commented
Protocol and URL Conventions are bundled together and have the ABNF and testcases as additional artifacts.

CSDL JSON has the JSON schema file as additional artifact, CSDL XML the two XML schema file.

JSON Format has no additional artifacts.

2024-02-27 14:18 UTC, HeikoTheissen submitted a review, later dismissed

2024-02-27 14:33 UTC, HeikoTheissen approved these changes

2024-02-28 15:50 UTC, HeikoTheissen approved these changes

2024-02-28 16:49 UTC, merged