ODATA-1435
oasis-tcs/odata-specs pull request #59
Opened 2023-07-28 15:39 UTC by HeikoTheissen

2023-08-16 07:52 UTC, ralfhandl requested changes
Small nit, otherwise fine

2023-08-16 07:52 UTC, ralfhandl commented on odata-csdl/14 Vocabulary and Annotation.md
> +if-then-else expression is collection-if-then-else expression, the third
```suggestion
if-then-else expression is a collection-if-then-else expression, the third
```

2023-08-16 08:34 UTC, ralfhandl submitted a review, later dismissed

2023-11-09 15:25 UTC, ralfhandl approved these changes

2023-11-30 08:10 UTC, ralfhandl submitted a review, later dismissed

2023-12-04 14:09 UTC, ralfhandl submitted a review, later dismissed

2024-01-26 09:09 UTC, ralfhandl submitted a review, later dismissed

2024-02-01 10:50 UTC, ralfhandl submitted a review, later dismissed

2024-02-15 08:00 UTC, ralfhandl submitted a review, later dismissed

2024-04-03 15:28 UTC, mikepizzo approved these changes

2024-04-03 15:30 UTC, merged

2024-04-03 15:32 UTC, mikepizzo commented
Fixes #326