ODATA-1498
oasis-tcs/odata-specs pull request #62
Opened 2023-07-31 11:29 UTC by HeikoTheissen

2023-08-15 15:40 UTC, ralfhandl commented
The intermediate file https://www.oasis-open.org/apps/org/workgroup/odata/download.php/70018/odata-json-format-v4.01-errata01.docx contained an additional paragraph in section 4.5.3 Control Information: type

> The type control information can be absent in properties nested in an instance of type `Edm.Untyped`. In particular, individual primitive values within a collection cannot have type control information.

Is this no longer necessary?

2023-08-15 16:21 UTC, HeikoTheissen commented
I have added it back, and also added the proposal made "after reopening".

2023-08-15 16:51 UTC, ralfhandl requested changes
Minor nit

2023-08-15 16:51 UTC, ralfhandl commented on odata-json-format/7 Structural Property.md
> +depending on the Javascript type.
```suggestion
depending on the JavaScript type.
```
Use same spelling as in all four other places

2023-08-15 16:57 UTC, ralfhandl submitted a review, later dismissed

2023-11-08 17:52 UTC, mikepizzo approved these changes

2023-11-08 17:53 UTC, merged